2020-11-18T22:33:47.9537760+03:00  [INF] User profile is available. Using '"/home/explosion204/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest. (a162847e)
2020-11-18T22:33:48.2072296+03:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-11-18T22:33:48.2074018+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-11-18T22:33:48.2095601+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-11-18T22:33:48.2096337+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-11-18T22:33:48.2096643+03:00  [INF] Content root path: "/home/explosion204/projects/craftwork-project/CraftworkProject.Web" (b5d60022)
2020-11-18T22:33:49.1318403+03:00 0HM4BV3FJRIDQ:0000000F [INF] Request starting HTTP/2 GET https://localhost:5001/   (ca22a1cb)
2020-11-18T22:33:49.1996021+03:00 0HM4BV3FJRIDQ:0000000F [INF] Executing endpoint '"CraftworkProject.Web.Controllers.HomeController.Index (CraftworkProject.Web)"' (500cc934)
2020-11-18T22:33:49.2587284+03:00 0HM4BV3FJRIDQ:0000000F [INF] Route matched with "{action = \"Index\", controller = \"Home\", area = \"\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Index()" on controller "CraftworkProject.Web.Controllers.HomeController" ("CraftworkProject.Web"). (122b2fdf)
2020-11-18T22:33:49.4106654+03:00 0HM4BV3FJRIDQ:0000000F [INF] Executed action "CraftworkProject.Web.Controllers.HomeController.Index (CraftworkProject.Web)" in 145.0722ms (afa2e885)
2020-11-18T22:33:49.4113346+03:00 0HM4BV3FJRIDQ:0000000F [INF] Executed endpoint '"CraftworkProject.Web.Controllers.HomeController.Index (CraftworkProject.Web)"' (99874f2b)
2020-11-18T22:33:49.4352518+03:00 0HM4BV3FJRIDQ:0000000F [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.Exception: Fuck you!
   at CraftworkProject.Web.Controllers.HomeController.Index() in /home/explosion204/projects/craftwork-project/CraftworkProject.Web/Controllers/HomeController.cs:line 22
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-11-18T22:33:49.4396812+03:00 0HM4BV3FJRIDQ:0000000F [ERR] Something went wrong: System.Exception: Fuck you!
   at CraftworkProject.Web.Controllers.HomeController.Index() in /home/explosion204/projects/craftwork-project/CraftworkProject.Web/Controllers/HomeController.cs:line 22
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task) (8c6678d2)
2020-11-18T22:33:49.5476543+03:00 0HM4BV3FJRIDQ:0000000F [INF] Request finished in 424.1476ms 500 application/json (791a596a)
